import {
  Bell,
  BellRing,
  Calendar,
  CalendarClock,
  CalendarPlus,
  CalendarX,
  FileText,
  MessageCircle,
  FlaskConical,
  CheckCircle2,
  XCircle,
  ClipboardList,
  AlarmClock,
  AlertTriangle,
  Megaphone,
  Receipt,
  Wallet,
} from 'lucide-react'
import type { AppNotification } from '@/types/notification'

export const NOTIFICATION_TYPE_ICONS: Record<AppNotification['type'], typeof Bell> = {
  appointment_booked: Calendar,
  appointment_cancelled: CalendarX,
  appointment_reminder: BellRing,
  chat_message: MessageCircle,
  medical_record_added: FileText,
  lab_result_ready: FlaskConical,
  shift_scheduled: CalendarPlus,
  shift_updated: CalendarClock,
  shift_cancelled: CalendarX,
  shift_application_approved: CheckCircle2,
  shift_application_rejected: XCircle,
  task_assigned: ClipboardList,
  task_due_soon: AlarmClock,
  task_overdue: AlertTriangle,
  announcement_published: Megaphone,
  invoice_created: Receipt,
  payment_received: Wallet,
}
