export const ROUTES = {
  login: '/login',
  verifyEmail: '/verify-email',
  oauthCallback: '/oauth/callback',
  selectRole: '/select-role',
  setPassword: '/set-password',
  dashboard: '/dashboard',
  staff: '/staff',
  patients: '/patients',
  doctors: '/doctors',
  appointments: '/appointments',
  beds: '/beds',
  laboratory: '/laboratory',
  pharmacy: '/pharmacy',
  billing: '/billing',
  reports: '/reports',
  settings: '/settings',
  messages: '/messages',
  medicalRecords: '/medical-records',
  findDoctor: '/find-doctor',
  bookAppointment: '/book-appointment',
  myAppointments: '/my-appointments',
  prescriptions: '/prescriptions',
} as const
